# neuralthreads
[medium](https://neuralthreads.medium.com/i-was-not-satisfied-by-any-deep-learning-tutorials-online-37c5e9f4bea1)

## Chapter 1 — Tensors

### 1.1 What are Tensors? (Tensors as NumPy arrays)

**Understanding the built of Tensors**

In a very simple language *‘Tensors’* are collections.

But, to understand their built, let us first see *‘Scalars’*.

First, let us import NumPy in Python.

In [5]:
import numpy as np
np.random.seed(42) # &&


**Scalars**

Scalars are simply numbers. For example, 5 is a scalar and so are 0.3 and -0.2
We can easily create a scalar in Python like this:

In [6]:
x = 5 # Scalar
print(x)

type(x)

5


int

**1-D Tensor or a Vector**

1-D Tensor or a vector is a *collection of Scalars*.

In [7]:
x = np.array([5, 0.3, -0.2])
print(x)

type(x) # NumPy array or a Tensor for us

[ 5.   0.3 -0.2]


numpy.ndarray

In [8]:
print(len(x.shape))
x.shape

1


(3,)

The length of the shape tuple is telling us that ‘x’ is a 1-D Tensor.

And, the shape tuple is telling us that in this 1-D Tensor, we have 3 scalar elements in it.

**2-D Tensor or a Matrix**

2-D Tensor or a Matrix is a collection of 1-D Tensors.

In [9]:
x = np.array([[5, 0.3, -0.2], [4, 3, 5], [0.1, 2, -0.56], [1, 1.2, 1.23]])
print(x)
type(x)

[[ 5.    0.3  -0.2 ]
 [ 4.    3.    5.  ]
 [ 0.1   2.   -0.56]
 [ 1.    1.2   1.23]]


numpy.ndarray

In [10]:
print(len(x.shape))
x.shape

2


(4, 3)

The length of the shape tuple is telling us that ‘x’ is a 2-D Tensor or a Matrix.

And, in this 2-D Tensor, we have 4 1-D Tensors, and in every 1-D Tensor, there are 3 scalar elements.

**3-D Tensor**

3-d Tensor is a collection of 2-D Tensors.

In [11]:
x = np.array([[[5, 0.3, -0.2], [4, 3, 5], [0.1, 2, -0.56], [1, 1.2, 1.23]], [[1, 2, 3], [0.1, 0.2, 0.3], [4, 5, 6], [0.4, 0.5, 0.6]]])
print(x)
print(len(x.shape))
x.shape

[[[ 5.    0.3  -0.2 ]
  [ 4.    3.    5.  ]
  [ 0.1   2.   -0.56]
  [ 1.    1.2   1.23]]

 [[ 1.    2.    3.  ]
  [ 0.1   0.2   0.3 ]
  [ 4.    5.    6.  ]
  [ 0.4   0.5   0.6 ]]]
3


(2, 4, 3)

The length of the shape tuple is telling us that ‘x’ is a 3-D Tensor.

And the shape tuple is telling us that in this 3-D Tensor we have 2 2-D Tensors, each 2-D Tensor has 4 1-D Tensors and each 1-D Tensor has 3 scalar elements in it.

**4-D Tensor**

4-D Tensor is a collection of 3-D Tensors.

In [12]:
x = np.array([[[[5, 0.3, -0.2], [4, 3, 5], [0.1, 2, -0.56], [1, 1.2, 1.23]],\
                [[1, 2, 3], [0.1, 0.2, 0.3], [4, 5, 6], [0.4, 0.5, 0.6]]], \
                    [[[5, 0.3, -0.2], [4, 3, 5], [0.1, 2, -0.56], [1, 1.2, 1.23]],\
                      [[1, 2, 3], [0.1, 0.2, 0.3], [4, 5, 6], [0.4, 0.5, 0.6]]]])
print(x)
print(len(x.shape))
x.shape

[[[[ 5.    0.3  -0.2 ]
   [ 4.    3.    5.  ]
   [ 0.1   2.   -0.56]
   [ 1.    1.2   1.23]]

  [[ 1.    2.    3.  ]
   [ 0.1   0.2   0.3 ]
   [ 4.    5.    6.  ]
   [ 0.4   0.5   0.6 ]]]


 [[[ 5.    0.3  -0.2 ]
   [ 4.    3.    5.  ]
   [ 0.1   2.   -0.56]
   [ 1.    1.2   1.23]]

  [[ 1.    2.    3.  ]
   [ 0.1   0.2   0.3 ]
   [ 4.    5.    6.  ]
   [ 0.4   0.5   0.6 ]]]]
4


(2, 2, 4, 3)

The length of the shape tuple is telling us that ‘x’ is a 4-D Tensor.

And, the shape tuple is telling us that in this 4-D Tensor, there are 2 3-D Tensors, in each 3-D Tensor, there are 2 2-D Tensors, in each 2-D Tensor, there are 4 1-D Tensor and in each 1-D Tensor, there are 3 scalar elements.

And so on .... 

**How to access a scalar element or a smaller dimension tensor?**

First, let us create a 4-D Tensor for demonstration.

In [13]:
x = np.array([[[[5, 0.3, -0.2], [4, 3, 5], [0.1, 2, -0.56], [1, 1.2, 1.23]], [[1, 2, 3], [0.1, 0.2, 0.3], [4, 5, 6], [0.4, 0.5, 0.6]]], [[[5, 0.3, -0.2], [4, 3, 5], [0.1, 2, -0.56], [1, 1.2, 1.23]], [[1, 2, 3], [0.1, 0.2, 0.3], [4, 5, 6], [0.4, 0.5, 0.6]]]])
print(x)
print(len(x.shape))
x.shape

[[[[ 5.    0.3  -0.2 ]
   [ 4.    3.    5.  ]
   [ 0.1   2.   -0.56]
   [ 1.    1.2   1.23]]

  [[ 1.    2.    3.  ]
   [ 0.1   0.2   0.3 ]
   [ 4.    5.    6.  ]
   [ 0.4   0.5   0.6 ]]]


 [[[ 5.    0.3  -0.2 ]
   [ 4.    3.    5.  ]
   [ 0.1   2.   -0.56]
   [ 1.    1.2   1.23]]

  [[ 1.    2.    3.  ]
   [ 0.1   0.2   0.3 ]
   [ 4.    5.    6.  ]
   [ 0.4   0.5   0.6 ]]]]
4


(2, 2, 4, 3)

To access a scalar element of a Tensor, you have to provide indexes equal to the number of dimensions of the Tensor.

In [14]:
print(type(x[0][0][2][1]))
print(x[0][0][2][1]) # expect 2.0
print(x[1][1][3][2]) # expect 0.6


<class 'numpy.float64'>
2.0
0.6


If the indexes are less than the number of dimensions, then we will be selecting a smaller dimension tensor.

In [15]:
print(x[0][1])
print(len(x[0][1].shape))
print(x[0][1].shape)
type(x[0][1])

[[1.  2.  3. ]
 [0.1 0.2 0.3]
 [4.  5.  6. ]
 [0.4 0.5 0.6]]
2
(4, 3)


numpy.ndarray

Here, we are selecting the second matrix from the first 3-D Tensor.

Let us take one final example.

In [16]:
x = np.random.randint(0, 2, (2, 3, 4, 5, 6, 5, 6)) 
print(x)
print(type(x))
print(len(x.shape))
print(x.shape)

[[[[[[[0 1 0 0 0 1]
      [0 0 0 1 0 0]
      [0 0 1 0 1 1]
      [1 0 1 0 1 1]
      [1 1 1 1 1 1]]

     [[0 0 1 1 1 0]
      [1 0 0 0 0 0]
      [1 1 1 1 1 0]
      [1 1 0 1 0 1]
      [0 1 1 0 0 0]]

     [[0 0 0 0 0 1]
      [1 0 1 1 1 1]
      [0 1 0 1 1 1]
      [0 1 0 1 0 1]
      [0 0 1 0 1 1]]

     [[1 1 1 1 1 1]
      [1 1 1 0 0 1]
      [1 1 1 1 1 1]
      [1 0 1 0 1 1]
      [0 1 0 1 1 0]]

     [[1 0 1 0 0 1]
      [1 0 1 1 1 0]
      [0 0 0 0 0 0]
      [0 0 1 0 1 1]
      [1 0 0 0 0 1]]

     [[0 0 0 0 0 1]
      [0 1 0 1 0 0]
      [1 1 1 0 1 0]
      [0 1 1 0 0 1]
      [1 1 0 0 0 0]]]


    [[[0 0 1 0 0 0]
      [1 0 0 1 0 0]
      [0 0 0 1 1 1]
      [0 0 0 1 0 0]
      [1 0 1 1 1 0]]

     [[0 0 0 0 0 0]
      [1 0 1 0 0 0]
      [1 1 1 1 0 1]
      [0 0 1 1 1 1]
      [1 1 1 1 0 1]]

     [[1 0 1 0 0 1]
      [0 0 0 0 1 0]
      [1 0 0 0 0 1]
      [1 0 0 1 0 0]
      [0 1 1 1 0 0]]

     [[1 1 1 1 0 1]
      [0 1 0 1 1 1]
      [1 0 1 0 0 0]
      [0 1 0 0 0 1]


We are generating a NumPy array of a given shape of integers from 0 to 2(excluding).

The length of the shape tuple is telling ‘x’ is a 7-D Tensor.

And in this tensor, there are 
- 2 6-D tensors, in each 6-D tensors, there are 
- 3 5-D tensors, in each 5-D tensor, there are 
- 4 4-D tensors, in each 4-D tensors, there are 
- 5 3-D tensors, in each 3-D tensor, there are 
- 6 2-D tensors, in each 2-D tensor, there are 
- 5 1-D tensors, and in each 1-D tensor, there are 
- 6 scalar elements.

**Understanding the built of Tensors from right to left**

We have understood the NumPy array or Tensor built from left to right. Now, let us understand from right to left.

First, we create a 3-D tensor.

In [17]:
x = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]], [[13, 14], [15, 16], [17, 18]], [[19, 20], [21, 22], [23, 24]]])
print(x)
print(len(x.shape))
print(x.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]
3
(4, 3, 2)


In [18]:
%%latex

\begin{align}
    \begin{array}{rl}
        \left [\, 1, \, 2 \right ] \Rightarrow \text{Shape = (2,)} \\
    \end{array}
    \\
    \left [ \begin{array}{r} 
            \left [ \begin{array}{rl}
                1, \, 2
            \end{array}  \right ],\\        
            \left [ \begin{array}{rl}
                3, \, 4
            \end{array}  \right ],\\ 
            \left [ \begin{array}{rl}
                5, \, 6
            \end{array}  \right ],\\ 
    \end{array} \right ] \Rightarrow \text{Shape = (3,2)} \\
       \\
    \left [ \begin{array}{r} 
        \left [ \begin{array}{r} 
            \left [ \begin{array}{rl}
                1, \, 2
            \end{array}  \right ],\\        
            \left [ \begin{array}{rl}
                3, \, 4
            \end{array}  \right ],\\ 
            \left [ \begin{array}{rl}
                5, \, 6
            \end{array}  \right ],\\ 
        \end{array} \right ] \\
        \left [ \begin{array}{r} 
            \left [ \begin{array}{l}
                7, \, 8
            \end{array}  \right ],\\        
            \left [ \begin{array}{rl}
                9, \, 10
            \end{array}  \right ],\\ 
            \left [ \begin{array}{l}
                11, \, 12
            \end{array}  \right ],\\ 
        \end{array} \right ] 
\\
        \left [ \begin{array}{r} 
            \left [ \begin{array}{rl}
                13, \, 14
            \end{array}  \right ],\\        
            \left [ \begin{array}{rl}
                15, \, 16
            \end{array}  \right ],\\ 
            \left [ \begin{array}{rl}
                17, \, 18
            \end{array}  \right ],\\ 
        \end{array} \right ] \\
        \left [ \begin{array}{r} 
            \left [ \begin{array}{l}
                19, \, 20
            \end{array}  \right ],\\        
            \left [ \begin{array}{rl}
                21, \, 22
            \end{array}  \right ],\\ 
            \left [ \begin{array}{l}
                23, \, 24
            \end{array}  \right ],\\ 
        \end{array} \right ] 
    \end{array} \right ]
    
    
    \Rightarrow \text{Shape = (4,3,2)} \\


\end{align}


<IPython.core.display.Latex object>

**Concept of Axis**

In [19]:
x = np.array([[[1, 2], [3, 4], [5, 6]], [[7, 8], [9, 10], [11, 12]], [[13, 14], [15, 16], [17, 18]], [[19, 20], [21, 22], [23, 24]]])
print(x)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


The number of Axis we have is equal to the dimension of the Tensor. In this case, we have a total of 3 Axis(es). Axis starts from 0.

**Axis 0**


In [20]:
print(x.shape)

(4, 3, 2)


Axis 0 refers to the first element in the shape tuple, which is actually all the N-1 D tensors in the N-D tensor. (4)

**Axis  1**

Axis 1 refers to the second element in the shape tuple, which is actually all the N-2 D tensors in all N-1 D tensors. (3)

**Axis 2**

Axis 2 refers to the third element in the shape tuple, which is actually all the N-3 D tensors in all N-2 D tensors. (2)

In this case, it is all the ***scalars*** in all of the vectors.

> Note — Axis = -1 can also be used for this case because -1 represents the last element in the tuple. In this case, it happens to be the third entry.

**A small comparison**

This is a small comparison between three tensors.

*First, (4, 1)*

The length of the shape tuple is telling ‘x’ is a 2-D Tensor.

And in this tensor, there are 
- 4 1-D tensors, and in each 1-D tensor, there are 
- 1 scalar elements.

In [21]:
x1 = np.array([[1], [2], [3], [4]])
print(x1)
print(len(x1.shape))
x1.shape

[[1]
 [2]
 [3]
 [4]]
2


(4, 1)

*Second, (4,)*

The length of the shape tuple is telling ‘x’ is a 1-D Tensor.

And in this tensor, there are 
- 4 scalar elements.

In [22]:
x2 = np.array([1, 2, 3, 4])
print(x2)
print(len(x2.shape))
x2.shape

[1 2 3 4]
1


(4,)

*Third, (1, 4)*

The length of the shape tuple is telling ‘x’ is a 2-D Tensor.

And in this tensor, there are 
- 1 1-D tensors, and in each 1-D tensor, there are 
- 4 scalar elements.

In [23]:
x3 = np.array([[1, 2, 3, 4]])
print(x3)
print(len(x3.shape))
x3.shape

[[1 2 3 4]]
2


(1, 4)

I hope now you understand the difference between (4, 1), (4, ) and, (1, 4) and how Tensors are built.

The goal of this chapter is to help you understand how we will build the Neural Network.