# neuralthreads
[medium](https://neuralthreads.medium.com/i-was-not-satisfied-by-any-deep-learning-tutorials-online-37c5e9f4bea1)

## Chapter 5 — Diving Deep in the Neural Networks

Building your own Neural Network — Understand the built of a Neural Network

With this post, we will be starting the fifth chapter in which we will first understand how Neural Networks are built, and then in the following posts we will go through the Backpropagation, L1 and L2 regularization, Layer Normalization, Batch Training, and much more.

> Note — This post uses many things from the previous chapters. It is recommended that you have a look at the previous posts.

### 5.1 Forward Feed in ANNs

Forward feed simply means calculating loss or y_hat (y predicted).

But first, we must understand how to make a Neural Network.

Neural Networks stores information or general pattern in parameters called ‘Weights’ and ‘Biases’.

Neural Networks consist of ‘Layers’ and each layer has ‘Nodes’.

![Layer with Nodes](image-1.png)  
*Layer with Nodes*

Each circle is a ‘Node’ and this collection of nodes is called a ‘Layer’.

Each node is represented by a scalar in Python and a collection of nodes in shape (-1, 1) forms a layer.

> Note — We can also create a Neural Network where a layer is of shape (-1,) or (1, -1) but in this course, we will make layers in shape (-1, 1).

Neural Networks can have as many layers and nodes as you want.

For this course, We will have the following architecture, i.e., 4 layers with 5, 3, 5, and 4 nodes respectively.

![4 Layers with 5, 3, 5, and 4 Nodes for the Neural Network](image-2.png)  
*4 Layers with 5, 3, 5, and 4 Nodes for the Neural Network*

The first layer is called the ‘*Input Layer*’

![Input Layer](image-3.png)  
*Input Layer*

The last layer is called the ‘*Output Layer*’.

![Output Layer](image-4.png)  
*Output Layer*

Layers in between them are called the ‘Hidden Layers’.

![Hidden Layers](image-5.png)  
*Hidden Layers*

Layers are connected to each other via ‘Weights’.

![Layers connected via weights](image-6.png)  
*Layers connected via weights*

Let us call the collection of weights ‘w1’, ‘w2’, and ‘w3’

![weights ‘w1’, ‘w2’, and ‘w3’](image-7.png)  
*weights ‘w1’, ‘w2’, and ‘w3’*

And we call each weight by nodes which they are connecting.
For example, this weight is called ‘w3₁₂’ because it connects the first node from the previous layer to the second node in the next layer.

![weight w3₁₂](image-8.png)   
*weight w3₁₂*

And each node in every layer except the input layer has a bias.
Let us call the collections of biases ‘b1’, ‘b2’, and ‘b3’.

![biases](image-9.png)  
*biases*

And we call each bias by what node it is connected to.
For example, this bias is called ‘b3₄’ because it is connected to the fourth node.

![bias b3₄](image-10.png)  
*bias b3₄*

Every hidden layer and the output layer is passed through an activation function.

![Activation layers](image-11.png)  
*Activation layers*

And finally, we have a layer that represents true output and a loss function.

![True output and a loss function](image-12.png)  
*True output and a loss function*

Let us name each layer one by one which will help us in making this Neural Network in Python.

First, we have the input Layer ‘x’. The elements will be x₁, x₂ …

![Input layer ‘x’ with elements x₁, x₂…..](image-13.png)  
*Input layer ‘x’ with elements x₁, x₂…..*

Then we have the input of the hidden 1 layer calling it ‘in_hidden_1’ or ‘I_H1’. The elements will be ‘I_H1₁’, ‘I_H1₂’ …

![in_hidden_1 layer ‘I_H1’ with elements ‘I_H1₁’, ‘I_H1₂’ …](image-14.png)  
*in_hidden_1 layer ‘I_H1’ with elements ‘I_H1₁’, ‘I_H1₂’ …*

Then an Activation layer for the first hidden layer.

![Activation layer for the first hidden layer](image-15.png)  
*Activation layer for the first hidden layer*

Then we have the output of hidden layer 1 calling it ‘out_hidden_1’ or ‘O_H1’. The elements will be ‘O_H1₁’, ‘O_H1₂’ …

![out_hidden_1 layer ‘O_H1’ with elements ‘O_H1₁’, ‘O_H1₂’ …](image-16.png)  
*out_hidden_1 layer ‘O_H1’ with elements ‘O_H1₁’, ‘O_H1₂’ …*

Then we have the input of the hidden 2 layer calling it ‘in_hidden_2’ or ‘I_H2’. The elements will be ‘I_H2₁’, ‘I_H2₂’ …

![in_hidden_2 layer ‘I_H2’ with elements ‘I_H2₁’, ‘I_H2₂’ …](image-17.png)  
*in_hidden_2 layer ‘I_H2’ with elements ‘I_H2₁’, ‘I_H2₂’ …*

Then an Activation layer for the second hidden layer.

![Activation layer for the second hidden layer](image-18.png)  
*Activation layer for the second hidden layer*

Then we have the output of hidden layer 2 calling it ‘out_hidden_2’ or ‘O_H2’. The elements will be ‘O_H2₁’, ‘O_H2₂’ …

![out_hidden_2 layer ‘O_H2’ with elements ‘O_H2₁’, ‘O_H2₂’ …](image-19.png)  
*out_hidden_2 layer ‘O_H2’ with elements ‘O_H2₁’, ‘O_H2₂’ …*

Then we have the input for the output layer calling it ‘in_output_layer’ or ‘I_OL’. The elements will be ‘I_OL₁’, ‘I_OL₂’ …

![in_ouput_layer ‘I_OL’ with elements ‘I_OL₁’, ‘I_OL₂’ …](image-20.png)  
*in_ouput_layer ‘I_OL’ with elements ‘I_OL₁’, ‘I_OL₂’ …*

Then an Activation layer for the output layer.

![Activation layer for the output layer](image-21.png)  
*Activation layer for the output layer*

Then we have the ‘y_hat’ or ‘y predicted’ layer. The elements will be ‘y_hat₁’, ‘y_hat₂’ …

![‘y_hat’ or ‘y_predicted’ layer with elements ‘y_hat₁’, ‘y_hat₂’ …](image-22.png)
*‘y_hat’ or ‘y_predicted’ layer with elements ‘y_hat₁’, ‘y_hat₂’ …*

Then we have a loss function.

![Loss function](image-23.png)
*Loss function*

And finally, we have the true output layer calling it ‘y’. The elements will be ‘y₁’, ‘y₂’ …

![true output layer ‘y’ with elements ‘y₁’, ‘y₂’ …](image-24.png)
*true output layer ‘y’ with elements ‘y₁’, ‘y₂’ …*




Our Neural Network will look like this.

![Our Neural Network](image-25.png)  
*Our Neural Network*

### Now let us start a forward feed or let us calculate the loss.

> Note — We can see that the shape of each layer is (-1, 1)

How will we do it? Simple, let us see each step one by one in Python.

But first a few things.  
**First**, the activation function for the first hidden layer is the ‘ReLU activation function with leak = 0.1’.  
**Second**, the activation function for the second hidden layer and the output layer is the ‘Sigmoid activation function’.  
**Third**, the loss function used is ‘Mean Square Error’.  

![Our Neural Network detailed](image-26.png)  
*Our Neural Network detailed*

Can you calculate the total number of parameters, i.e., weights and biases? It is easy to come up with a formula.

So, the steps are:

> Step 1 - Importing NumPy library and defining nodes in each layer  
> Step 2 - Inputs and true Outputs  
> Step 3 - Defining the Activation functions and the loss function  
> Step 4 - Random initialization of weights and zero initialization of biases  
> Step 5 - Calculating outputs of each layer  
> Step 6 - Calculating the loss or error

Let us see each step one by one.

### Step 1 — Importing NumPy library and defining nodes in each layer

In [3]:
import numpy as np                          # importing NumPy
np.random.seed(42)

input_nodes = 5                             # nodes in each layer
hidden_1_nodes = 3
hidden_2_nodes = 5
output_nodes = 4

### Step 2 — Inputs and true Outputs

In [4]:
x = np.random.randint(1, 100, size = (input_nodes, 1)) / 100
print('x')                                  # Inputs
print(x, x.shape)

y = np.random.randint(1, 100, size = (output_nodes, 1)) / 100
print('y')                                  # Outputs
print(y, y.shape)

x
[[0.52]
 [0.93]
 [0.15]
 [0.72]
 [0.61]] (5, 1)
y
[[0.21]
 [0.83]
 [0.87]
 [0.75]] (4, 1)


### Step 3 — Defining the Activation functions and the loss function

In [5]:
def relu(x, leak = 0):                      # ReLU
    return np.where(x <= 0, leak * x, x)

def sig(x):                                 # Sigmoid
    return 1/(1 + np.exp(-x))

def mse(y_true, y_pred):                    # MSE
    return np.mean((y_true - y_pred)**2)

### Step 4 — Random initialization of weights and zero initialization of biases

> Note — Weights are generally initialized between -1 and 1 such that the mean is 0 and the standard deviation is 1. But here we will initialize them randomly between 0 and 1. We will generate normally distributed weights in the last post of this chapter where we will talk about the UCI White Wine quality dataset. There are many other ways to initialize the weights and biases. You may refer to the literature available on the internet.

But first, we will understand what will be the shape of the weight tensors.

The shape of the weight tensor will be:  
**(nodes in the next layer, nodes in the previous layer)**

So for weights w1, we will have a matrix of shape (3, 5)

![weights w1](image-27.png)  
*weights w1*

We can see that the first column in the weight matrix represents the outgoing weights from the first node of the previous layer and the first row represents incoming weights to the first node in the next layer.

Let us take a look one more time.

![w1,b1](image-28.png)

The second column represents the outgoing weights from the second node in the previous layer.

![second column](image-29.png)

The second row represents incoming weights to the second node in the next layer.

![second row](image-30.png)

So, the shape of the *weight matrix* will be  
**(nodes in the next layer, nodes in the previous layer)**  
and the shape of *biases* will be 
**(-1, 1)** or **(nodes in the layer, 1)**

So,

In [21]:
w1 = np.random.random(size = (hidden_1_nodes, input_nodes))
b1 = np.zeros(shape = (hidden_1_nodes, 1))
print('w1')                                 # w1
print(w1, w1.shape)
print('\n')
print('b1')                                 # b1
print(b1, b1.shape)
w2 = np.random.random(size = (hidden_2_nodes, hidden_1_nodes))
b2 = np.zeros(shape = (hidden_2_nodes, 1))
print('w2')                                 # w2
print(w2, w2.shape)
print('\n')
print('b2')                                 # b2
print(b2, b2.shape)
w3 = np.random.random(size = (output_nodes, hidden_2_nodes))
b3 = np.zeros(shape = (output_nodes, 1))
print('w3')                                 # w3
print(w3, w3.shape)
print('\n')
print('b3')                                 # b3
print(b3, b3.shape)

w1
[[0.03142919 0.63641041 0.31435598 0.50857069 0.90756647]
 [0.24929223 0.41038292 0.75555114 0.22879817 0.07697991]
 [0.28975145 0.16122129 0.92969765 0.80812038 0.63340376]] (3, 5)


b1
[[0.]
 [0.]
 [0.]] (3, 1)
w2
[[0.87146059 0.80367208 0.18657006]
 [0.892559   0.53934224 0.80744016]
 [0.8960913  0.31800347 0.11005192]
 [0.22793516 0.42710779 0.81801477]
 [0.86073058 0.00695213 0.5107473 ]] (5, 3)


b2
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]] (5, 1)
w3
[[0.417411   0.22210781 0.11986537 0.33761517 0.9429097 ]
 [0.32320293 0.51879062 0.70301896 0.3636296  0.97178208]
 [0.96244729 0.2517823  0.49724851 0.30087831 0.28484049]
 [0.03688695 0.60956433 0.50267902 0.05147875 0.27864646]] (4, 5)


b3
[[0.]
 [0.]
 [0.]
 [0.]] (4, 1)


### Step 5 — Calculating outputs of each layer

### 5.1 Calculating ‘in_hidden_1’ or ‘I_H1’

To calculate outputs of each layer, we take a weighted sum like this

![I_H1](image-31.png)

![formulas](image-32.png)

We can use matrix multiplication to reduce it so that we can implement it in Python like this

![](image-33.png)

In [22]:
in_hidden_1 = w1.dot(x) + b1
print('in_hidden_1')
print(in_hidden_1, in_hidden_1.shape)

in_hidden_1
[[1.5751447 ]
 [0.83631317]
 [1.40828417]] (3, 1)


### 5.2 Calculating ‘out_hidden_1’ or ‘O_H1’

We can calculate ‘O_H1’ by passing it through the ReLU activation function with leak = 0.1

![O_H1](image-34.png)

In [34]:
%%latex
\begin{gather*}
    O\_H1 = relu(I\_H1, leak = 0.1)
\end{gather*}

<IPython.core.display.Latex object>

In [23]:
out_hidden_1 = relu(in_hidden_1, leak = 0.1)
print('out_hidden_1')
print(out_hidden_1, out_hidden_1.shape)

out_hidden_1
[[1.5751447 ]
 [0.83631317]
 [1.40828417]] (3, 1)


### 5.3 Calculating ‘in_hidden_2’ or ‘I_H2’

![I_H2](image-36.png)

![Alt text](image-37.png)

Or, we can do

![](image-38.png)

In [24]:
in_hidden_2 = w2.dot(out_hidden_1) + b2
print('in_hidden_2')
print(in_hidden_2, in_hidden_2.shape)

in_hidden_2
[[2.30754174]
 [2.99407378]
 [1.83240834]
 [1.86822398]
 [2.08086672]] (5, 1)


### 5.4 Calculating ‘out_hidden_2’ or ‘O_H2’

![O_H2](image-39.png)

In [33]:
%%latex
\begin{gather*}
    O\_H2 = sig(I\_H2)
\end{gather*}

<IPython.core.display.Latex object>

In [25]:
out_hidden_2 = sig(in_hidden_2)
print('out_hidden_2')
print(out_hidden_2, out_hidden_2.shape)

out_hidden_2
[[0.90949972]
 [0.95230568]
 [0.86204838]
 [0.86625264]
 [0.88902957]] (5, 1)


### 5.5 Calculating ‘in_output_layer’ or ‘I_OL’

![](image-41.png)

![](image-42.png)

or, we can do this

![](image-43.png)

In [26]:
in_output_layer = w3.dot(out_hidden_2) + b3
print('in_output_layer')
print(in_output_layer, in_output_layer.shape)

in_output_layer
[[1.82521411]
 [2.5729747 ]
 [2.05763978]
 [1.33969243]] (4, 1)


### 5.6 Calculating ‘y_hat’

![](image-44.png)

In [32]:
%%latex
\begin{gather*}
    \hat{y} = sig(I\_OL)
\end{gather*}


<IPython.core.display.Latex object>

In [27]:
y_hat = sig(in_output_layer)
print('y_hat')
print(y_hat, y_hat.shape)

y_hat
[[0.8611906 ]
 [0.92910189]
 [0.8867173 ]
 [0.79243936]] (4, 1)


We can print true values or ‘y’ to see how different the predicted values are from true values

In [28]:
print('y')
print(y, y.shape)

y
[[0.21]
 [0.83]
 [0.87]
 [0.75]] (4, 1)


### Step 6 — Calculating MSE loss or error

![mse](image-46.png)

In [29]:
mse(y, y_hat)

0.10898773857793441

So, I hope now you understand how to build your own Neural Network.

I am not using Object-Oriented programming because I want to keep things simple for this course.

In the next two posts, we will see how to use Backpropagation to calculate gradients which will help us to minimize the loss by updating weights and biases with the help of some Optimizer.

If you are looking for Batch training then you have to wait for the sixth post of this chapter.

//-----------------------//