# neuralthreads
[medium](https://neuralthreads.medium.com/i-was-not-satisfied-by-any-deep-learning-tutorials-online-37c5e9f4bea1)

## Chapter 1 — Tensors

### 1.2 What is Tensor reshaping?

> Note — It is recommended that you have a look at the previous post (own_tutorial_1.ipynb).

Tensor reshaping is simply changing the shape of the Tensor or doing partition of tensor in various ways.

Let us start with creating a 2-D Tensor of shape (6, 4). For the sake of clarity, the elements are 1 to 24 in ascending order. Believe me, this order will play a significant role in understanding Tensor reshaping.

*Creating a 2-D tensor*

In [2]:
import numpy as np
np.random.seed(42)
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [3]:
print(len(x.shape))
print(x.shape)
print(x.size)


2
(6, 4)
24


The total number of scalar elements in the Tensor is always equal to the product of numbers in the shape tuple. Here, it is 6 * 4 = 24

*x.size* also gives the total number of scalar elements

You must have noticed that while creating this 2-D Tensor, I wrote all the scalars and square brackets in one single line.

> ====>>> [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]] <<<====

Let us say at the beginning we have a vector containing scalar elements from 1 to 24 in ascending order.

> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]

Then we break it into 6 groups and apparently each group formed will have 4 scalars in it.

> [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]

This is how this *2-D Tensor* was created. We broke 24 into 6 and 4.

Can we break it into 4 and 6, or 8 and 3, or 3 and 8?

We can change the shape of the tensor to (8, 3) using this line of code.

In [4]:
print(x.reshape((8, 3)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]


In [5]:
print(x.reshape((3, 8)))

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]]


You can notice that the ascending order is still the same.

> Note — The shape of the array is still (6, 4) because we haven’t assigned reshaped tensor to a variable.

Similarly like this,

In [12]:
print('------------((12, 2)))--------------')
print(x.reshape((12, 2)))
print('-------------((2, 12)))---------------')
print(x.reshape((2, 12)))

------------((12, 2)))--------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]
 [21 22]
 [23 24]]
-------------((2, 12)))---------------
[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [14]:
print('----------((2, 3, 4)))-------------')
print(x.reshape((2, 3, 4)))
print('-----------((3, 4, 2)))-------------')
print(x.reshape((3, 4, 2)))

----------((2, 3, 4)))-------------
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
-----------((3, 4, 2)))-------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]

 [[17 18]
  [19 20]
  [21 22]
  [23 24]]]


In [16]:
print('-----------((4, 3, 2)))-------------')
print(x.reshape((4, 3, 2)))

-----------((4, 3, 2)))-------------
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]

 [[19 20]
  [21 22]
  [23 24]]]


We can change the shape of the tensor as long as the product of the numbers in the final shape tuple is equal to the total number of scalar elements in the tensor or the product of numbers in the original shape tuple.

> print(x.reshape((2, 13))) # 26
> print(x.reshape((2, 11))) # 22

will produce error because of

> 24 != 2 * 13 = 26
> 24 != 2*11 = 22

Going forward, we can break 24 into (2, 2, 1, 1, 1, 2, 3), or (3, 4, 1, 1, 1, 1, 1, 2)

In [18]:
print(x.reshape((2, 2, 1, 1, 1, 2, 3)))

[[[[[[[ 1  2  3]
      [ 4  5  6]]]]]




  [[[[[ 7  8  9]
      [10 11 12]]]]]]





 [[[[[[13 14 15]
      [16 17 18]]]]]




  [[[[[19 20 21]
      [22 23 24]]]]]]]


In [19]:
print(x.reshape((3, 4, 1, 1, 1, 1, 1, 2)))

[[[[[[[[ 1  2]]]]]]





  [[[[[[ 3  4]]]]]]





  [[[[[[ 5  6]]]]]]





  [[[[[[ 7  8]]]]]]]






 [[[[[[[ 9 10]]]]]]





  [[[[[[11 12]]]]]]





  [[[[[[13 14]]]]]]





  [[[[[[15 16]]]]]]]






 [[[[[[[17 18]]]]]]





  [[[[[[19 20]]]]]]





  [[[[[[21 22]]]]]]





  [[[[[[23 24]]]]]]]]


The ascending order is still unchanged.

During reshaping, every tensor is one single straight line in which the order of the scalar elements never changes but the position square brackets determine its shape.

And the way NumPy shows us these Tensors is like this:

- Scalars in a horizontal manner
- Other higher dimension elements in a vertical manner

the most important part of this post.

**What is the meaning of reshaping a tensor into (-1, 1), or (-1,), or (1, -1)?**

> (-1, 1)

When we reshape a tensor into (-1, 1)

-1 is equivalent to the total number of scalars divided by the positive number in the shape tuple.

In this case, it is 24 because 24 / 1 = 24

It is like reshaping into (24, 1)

This is useful when we have to convert the tensor to a 2-D Tensor in which the 1-D Tensor should have exactly 1 scalar element or like a column vector.



In [20]:
print(x.reshape((-1, 1)))
print(x.reshape(24, 1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]]


Reshaping to (-1, 1) is equivalent to reshaping it into (24, 1)

**(-1, )**

When we reshape it into (-1,) or flatten it

-1 is equivalent to the total number of scalars in the tensor.

Here, -1 is equivalent to 24. It is like converting the tensor to a vector.

In [21]:
print(x.reshape((-1)))
print(x.reshape((24,)))
print(x.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


Reshaping to (-1,) is equivalent to reshaping it into (24,), or flatten it

**(1, -1)**

When we reshape it to (1, -1)

-1 is equivalent to the total number of scalars divided by the positive number in the shape tuple.

In this case, it is 24 because 24 / 1 = 24

It is like reshaping into (1, 24)

In [22]:
print(x.reshape((1, -1)))
print(x.reshape(1, 24))

[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]]
[[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]]


Can you tell me what will happen if we reshape it to (2, -1, 3)?

In [23]:
print(x.reshape((2, -1, 3)))
x.reshape((2, -1, 3)).shape

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]]


(2, 4, 3)

It is equivalent to (2, 4, 3) because 24 / (2 * 3) = 4

I hope now you understand what is Tensor reshaping and what it means to convert it into (-1, 1), or (-1,), or (1, -1)?

We will use (-1, 1) throughout the course. It is will help us to understand how we will build Neural Networks.